const fs = require("fs");
const width = 500;
const height = 500;
const dir = __dirname;
const description = "The first NFT VC.";
const baseImageUri = "https://gateway.pinata.cloud/ipfs";
const startEditionFrom = 1;
const endEditionAt = 1000;
const editionSize = 1000;
const raceWeights = [
  {
    value: "skull",
    from: 1,
    to: editionSize,
  },
];

const races = {
  skull: {
    name: "Skull",
    layers: [
      {
        name: "Background",
        elements: [
          {
            id: 0,
            name: "White",
            path: `${dir}/1-background/White.png`,
            weight: 100,
          },
          {
            id: 1,
            name: "Red",
            path: `${dir}/1-background/Red.png`,
            weight: 50,
          },
          {
            id: 2,
            name: "Orange",
            path: `${dir}/1-background/Orange.png`,
            weight: 40,
          },
          {
            id: 3,
            name: "Yellow",
            path: `${dir}/1-background/Yellow.png`,
            weight: 32,
          },
          {
            id: 4,
            name: "Green",
            path: `${dir}/1-background/Green.png`,
            weight: 27,
          },
          {
            id: 5,
            name: "Blue",
            path: `${dir}/1-background/Blue.png`,
            weight: 18,
          },
          {
            id: 6,
            name: "Indigo",
            path: `${dir}/1-background/Indigo.png`,
            weight: 8,
          },
          {
            id: 7,
            name: "Violet",
            path: `${dir}/1-background/Violet.png`,
            weight: 2,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Shirt",
        elements: [
          {
            id: 0,
            name: "Black",
            path: `${dir}/2-shirt/black.png`,
            weight: 100,
          },
          {
            id: 1,
            name: "Blue",
            path: `${dir}/2-shirt/blue.png`,
            weight: 95,
          },
          {
            id: 2,
            name: "Bone",
            path: `${dir}/2-shirt/bone.png`,
            weight: 93,
          },
          {
            id: 3,
            name: "Brown",
            path: `${dir}/2-shirt/brown.png`,
            weight: 90,
          },
          {
            id: 4,
            name: "Coarl",
            path: `${dir}/2-shirt/coral.png`,
            weight: 88,
          },
          {
            id: 5,
            name: "Cream",
            path: `${dir}/2-shirt/cream.png`,
            weight: 85,
          },
          {
            id: 6,
            name: "Dark Navy",
            path: `${dir}/2-shirt/dark navy.png`,
            weight: 83,
          },
          {
            id: 7,
            name: "Green",
            path: `${dir}/2-shirt/green.png`,
            weight: 80,
          },
          {
            id: 8,
            name: "Grey",
            path: `${dir}/2-shirt/grey.png`,
            weight: 77,
          },
          {
            id: 9,
            name: "Ivory",
            path: `${dir}/2-shirt/ivory.png`,
            weight: 74,
          },
          {
            id: 10,
            name: "Light Blue",
            path: `${dir}/2-shirt/light blue.png`,
            weight: 72,
          },
          {
            id: 11,
            name: "Light Grey",
            path: `${dir}/2-shirt/light grey.png`,
            weight: 64,
          },
          {
            id: 12,
            name: "Light Pink",
            path: `${dir}/2-shirt/light pink.png`,
            weight: 59,
          },
          {
            id: 13,
            name: "Light Purple",
            path: `${dir}/2-shirt/light purple.png`,
            weight: 54,
          },
          {
            id: 14,
            name: "Maroon",
            path: `${dir}/2-shirt/maroon.png`,
            weight: 50,
          },
          {
            id: 15,
            name: "Navy Blue",
            path: `${dir}/2-shirt/navy.png`,
            weight: 47,
          },
          {
            id: 16,
            name: "Ocean",
            path: `${dir}/2-shirt/ocean.png`,
            weight: 43,
          },
          {
            id: 17,
            name: "Pink",
            path: `${dir}/2-shirt/pink.png`,
            weight: 40,
          },
          {
            id: 18,
            name: "Purple",
            path: `${dir}/2-shirt/purple.png`,
            weight: 38,
          },
          {
            id: 19,
            name: "Red",
            path: `${dir}/2-shirt/red.png`,
            weight: 35,
          },
          {
            id: 20,
            name: "White",
            path: `${dir}/2-shirt/white.png`,
            weight: 30,
          },
          {
            id: 21,
            name: "Yellow",
            path: `${dir}/2-shirt/yellow.png`,
            weight: 2,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Tie",
        elements: [
          {
            id: 0,
            name: "Aqua",
            path: `${dir}/3-tie/aqua.png`,
            weight: 100,
          },
          {
            id: 1,
            name: "Azure",
            path: `${dir}/3-tie/azure.png`,
            weight: 98,
          },
          {
            id: 2,
            name: "Barf",
            path: `${dir}/3-tie/barf.png`,
            weight: 96,
          },
          {
            id: 3,
            name: "Black Shiny",
            path: `${dir}/3-tie/black shiny.png`,
            weight: 94,
          },
          {
            id: 4,
            name: "Black Thin",
            path: `${dir}/3-tie/black thin.png`,
            weight: 92,
          },
          {
            id: 5,
            name: "Black",
            path: `${dir}/3-tie/black.png`,
            weight: 88,
          },
          {
            id: 6,
            name: "Blue Shiny",
            path: `${dir}/3-tie/blue shiny.png`,
            weight: 76,
          },
          {
            id: 7,
            name: "Blue Thin",
            path: `${dir}/3-tie/blue thin.png`,
            weight: 75,
          },
          {
            id: 8,
            name: "Blue",
            path: `${dir}/3-tie/blue.png`,
            weight: 74,
          },
          {
            id: 9,
            name: "Charcoal",
            path: `${dir}/3-tie/charcoal.png`,
            weight: 69,
          },
          {
            id: 10,
            name: "Chartreuse",
            path: `${dir}/3-tie/chartreuse.png`,
            weight: 65,
          },
          {
            id: 11,
            name: "Coral",
            path: `${dir}/3-tie/coral.png`,
            weight: 62,
          },
          {
            id: 12,
            name: "Dark Grey",
            path: `${dir}/3-tie/dark grey.png`,
            weight: 59,
          },
          {
            id: 13,
            name: "Dark Purple",
            path: `${dir}/3-tie/dark purple.png`,
            weight: 55,
          },
          {
            id: 14,
            name: "Dark Red",
            path: `${dir}/3-tie/dark red.png`,
            weight: 52,
          },
          {
            id: 15,
            name: "Mustard",
            path: `${dir}/3-tie/dark yellow.png`,
            weight: 49,
          },
          {
            id: 16,
            name: "Green",
            path: `${dir}/3-tie/green.png`,
            weight: 46,
          },
          {
            id: 17,
            name: "Grey Shiny",
            path: `${dir}/3-tie/grey shiny.png`,
            weight: 43,
          },
          {
            id: 18,
            name: "Grey Thin",
            path: `${dir}/3-tie/grey thin.png`,
            weight: 41,
          },
          {
            id: 19,
            name: "Grey",
            path: `${dir}/3-tie/grey.png`,
            weight: 40,
          },
          {
            id: 20,
            name: "Maroon",
            path: `${dir}/3-tie/maroon.png`,
            weight: 35,
          },
          {
            id: 21,
            name: "Navy Blue",
            path: `${dir}/3-tie/navy.png`,
            weight: 33,
          },
          {
            id: 22,
            name: "Orange",
            path: `${dir}/3-tie/orange.png`,
            weight: 30,
          },
          {
            id: 23,
            name: "Pink Thin",
            path: `${dir}/3-tie/pink thin.png`,
            weight: 2,
          },
          {
            id: 24,
            name: "Pink",
            path: `${dir}/3-tie/pink.png`,
            weight: 26,
          },
          {
            id: 25,
            name: "Purple",
            path: `${dir}/3-tie/purple.png`,
            weight: 24,
          },
          {
            id: 26,
            name: "Red Thin",
            path: `${dir}/3-tie/red thin.png`,
            weight: 21,
          },
          {
            id: 27,
            name: "Red",
            path: `${dir}/3-tie/red.png`,
            weight: 20,
          },
          {
            id: 28,
            name: "Salmon",
            path: `${dir}/3-tie/salmon.png`,
            weight: 16,
          },
          {
            id: 29,
            name: "Sky",
            path: `${dir}/3-tie/sky.png`,
            weight: 14,
          },
          {
            id: 30,
            name: "Teal Shiny",
            path: `${dir}/3-tie/teal shiny.png`,
            weight: 12,
          },
          {
            id: 31,
            name: "Violet",
            path: `${dir}/3-tie/violet.png`,
            weight: 11,
          },
          {
            id: 32,
            name: "White",
            path: `${dir}/3-tie/white.png`,
            weight: 8,
          },
          {
            id: 33,
            name: "Yellow",
            path: `${dir}/3-tie/yellow.png`,
            weight: 3,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Jacket",
        elements: [
          {
            id: 0,
            name: "Anchor",
            path: `${dir}/4-jacket/anchor.png`,
            weight: 100,
          },
          {
            id: 1,
            name: "Black",
            path: `${dir}/4-jacket/black.png`,
            weight: 95,
          },
          {
            id: 2,
            name: "Blue",
            path: `${dir}/4-jacket/blue.png`,
            weight: 82,
          },
          {
            id: 3,
            name: "Brown",
            path: `${dir}/4-jacket/brown.png`,
            weight: 78,
          },
          {
            id: 4,
            name: "Charcoal",
            path: `${dir}/4-jacket/charcoal.png`,
            weight: 75,
          },
          {
            id: 5,
            name: "Coin",
            path: `${dir}/4-jacket/coin.png`,
            weight: 65,
          },
          {
            id: 6,
            name: "Dark Blue",
            path: `${dir}/4-jacket/dark blue.png`,
            weight: 60,
          },
          {
            id: 7,
            name: "Dark Grey",
            path: `${dir}/4-jacket/dark grey.png`,
            weight: 55,
          },
          {
            id: 8,
            name: "Gold Shiny",
            path: `${dir}/4-jacket/gold.png`,
            weight: 47,
          },
          {
            id: 9,
            name: "Green",
            path: `${dir}/4-jacket/green.png`,
            weight: 46,
          },
          {
            id: 10,
            name: "Grey",
            path: `${dir}/4-jacket/grey.png`,
            weight: 41,
          },
          {
            id: 11,
            name: "Khaki",
            path: `${dir}/4-jacket/khaki.png`,
            weight: 36,
          },
          {
            id: 12,
            name: "Maroon",
            path: `${dir}/4-jacket/maroon.png`,
            weight: 34,
          },
          {
            id: 13,
            name: "Midnight",
            path: `${dir}/4-jacket/midnight.png`,
            weight: 30,
          },
          {
            id: 14,
            name: "Navy Blue",
            path: `${dir}/4-jacket/navy.png`,
            weight: 25,
          },
          {
            id: 15,
            name: "Pebble",
            path: `${dir}/4-jacket/pebble.png`,
            weight: 15,
          },
          {
            id: 16,
            name: "Pink",
            path: `${dir}/4-jacket/pink.png`,
            weight: 8,
          },
          {
            id: 17,
            name: "White",
            path: `${dir}/4-jacket/white.png`,
            weight: 5,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Pins",
        elements: [
          {
            id: 0,
            name: "None",
            path: `${dir}/5-pin/None.png`,
            weight: 100,
          },
          {
            id: 1,
            name: "ETH Pin",
            path: `${dir}/5-pin/eth.png`,
            weight: 6,
          },
          {
            id: 2,
            name: "ETH2 Pin",
            path: `${dir}/5-pin/eth2.png`,
            weight: 4,
          },
          {
            id: 3,
            name: "BTC Pin",
            path: `${dir}/5-pin/btc.png`,
            weight: 3,
          },
          {
            id: 4,
            name: "Dimond Pin",
            path: `${dir}/5-pin/dimond.png`,
            weight: 2,
          },
          {
            id: 5,
            name: "Unicorn Pin",
            path: `${dir}/5-pin/unicorn.png`,
            weight: 1,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
    ],
  },
};

module.exports = {
  width,
  height,
  description,
  baseImageUri,
  editionSize,
  startEditionFrom,
  endEditionAt,
  races,
  raceWeights,
};
